// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://givquwdvzvjqxkzucacw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpdnF1d2R2enZqcXhrenVjYWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTIwNjEsImV4cCI6MjA2NjI2ODA2MX0.VCE-k9asBGy0L3pqTFSqezb1odJBFY2P3axzWEiW4wQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);